### ISSUE TITLE
addition of vines only applies to regular vines

### ISSUE THREAD

**Issue by RyanCR03** [DomiIRL/FixedWaterlogging#1]
In the process of creating waterloggable vines, it can be assumed that you forgot to apply this to:

- weeping vines
- twisting vines
- cave vines (glowing vines)

Some other possible waterloggable blocks:

- torches
- soul torches
- saplings
- bamboo
- cobwebs
- double flowers (not grass)
- mushrooms
- chorus plant/flower
- shulker box
- composter
- dirt path
- redstone dust
- tripwire hook
- tripwire (string)
- beacon
- sugar cane
- barrier
- spawner
- turtle egg

**Comment by DomiIRL** [comment]
Cave Vines? Do you mean Glow Lichen? They are already waterloggable by vanilla

**Comment by RyanCR03** [comment]
i meant vines created by glowberries

**Comment by DomiIRL** [comment]
The problem is that these vines are different from the normal vine because these are two different blocks for each type. One Plant and one body block and as these are replaced with their default state everytime something happens its very hard to make the water not randomly disappearing.
I guess I'll try working on that sometime in the near future
