### ISSUE TITLE
Random Crash (made world corrupted)

### ISSUE THREAD

**Issue by Toilet-Lord** [DomiIRL/FixedWaterlogging#4]
Lost a week of progression in my world as I was walking through the jungle.

Heres the crash log..
[crash-2021-12-24_01.38.57-server.txt](https://github.com/KxmischesDomi/FixedWaterlogging/files/7773019/crash-2021-12-24_01.38.57-server.txt)

Also if you remove the mod, every block becomes another block, any fix for that?

**Comment by DomiIRL** [comment]
Have you updated to 1.0.3?

**Comment by Toilet-Lord** [comment]
Fuck. No I didn't, I update the mod after 1.0.2 came out BC the start-up crash was fixed then I didn't know you posted another update

**Comment by Toilet-Lord** [comment]
Sorry for the pessimistic message earlier, I'll check out the update in a few hours, thanks ❤️

**Comment by DomiIRL** [comment]
Yea I posted another update that should fix a few more things. The mod is still very buggy right now because I'm modifying a wide range of blocks and there are many things that some blocks can do different then others.

I'm very sorry that you lost your world but what exactly happend? 
So you just can't open it anymore? Then I guess there was a modded block in that jungle that keeps the game crashing right?

And with the different blocks, I saw that happen when you join a server without the mod with a client with the mod, but it was only a client issue and removing the mod from a singleplayer world and loading it again wasn't any problem for me either.
Can you try to test if the blocks are only changed clientside or also serverside? It would be a serious issue if the mod somehow corrupts complete worlds
